// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Security.Principal;
using static CrossingCat.Domain.Enums.Enums;

namespace CrossingCats.Infrastructure.Models;

public partial class Player
{
    public int Id { get; set; }
    
    public Roles Role { get; set; }

    public int AccountId { get; set; }

    public int GameId { get; set; }

    public virtual User Account { get; set; }

    public virtual Game Game { get; set; }
}