// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrossingCats.Infrastructure.Models;

public partial class User
{
    public int Id { get; set; }

    public int TotalGames { get; set; }

    public int TotalCatGames { get; set; }

    public int TotalCarGames { get; set; }

    public int Score { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public virtual Player Player { get; set; }
}