// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using static CrossingCat.Domain.Enums.Enums;

namespace CrossingCats.Domains.Models;

public  class PlayerDto
{
    public int Id { get; set; }

    public Roles Role { get; set; }

    public int AccountId { get; set; }

    public int GameId { get; set; }

    public  UserDto Account { get; set; }

    public  GameDto Game { get; set; }
}